/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases.libreria;

import javax.swing.*;

public class FormMenuPrincipal extends javax.swing.JFrame {
    
    private String idUsuario;
    private String nombreUsuario;
    private String nombreCargo; // CAMBIO: Era rolUsuario

    public FormMenuPrincipal(String idUsuario, String nombreUsuario, String nombreCargo) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombreCargo = nombreCargo; // CAMBIO
        
        initComponents();
        configurarMenuSegunCargo(); // CAMBIO: Era configurarMenuSegunRol
        setLocationRelativeTo(null);
    }
    
    public FormMenuPrincipal() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGestionarProductores = new javax.swing.JButton();
        btnGestionarPredios = new javax.swing.JButton();
        btnRegistrarPlaga = new javax.swing.JButton();
        btnGestionarCatalogos = new javax.swing.JButton();
        btnGestionarTecnicos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Sistema de Gestión Agrícola");

        lblBienvenida.setText("Bienvenido: Usuario");

        lblCargo.setText("Rol: ADMINISTRADOR");

        btnGestionarProductores.setText("📋 Gestionar Productores");
        btnGestionarProductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProductoresActionPerformed(evt);
            }
        });

        btnGestionarPredios.setText("🏡 Gestionar Predios Registrados");
        btnGestionarPredios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPrediosActionPerformed(evt);
            }
        });

        btnRegistrarPlaga.setText("📝 Registrar Plaga");
        btnRegistrarPlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPlagaActionPerformed(evt);
            }
        });

        btnGestionarCatalogos.setText("📚 Gestionar Catálogos de Plagas y Cultivos");
        btnGestionarCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCatalogosActionPerformed(evt);
            }
        });

        btnGestionarTecnicos.setText("👨‍🔬 Gestionar Usuarios");
        btnGestionarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTecnicosActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("🚪 Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarPlaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarPredios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarCatalogos, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenida)
                            .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarProductores)
                    .addComponent(btnGestionarPredios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPlaga)
                    .addComponent(btnGestionarCatalogos))
                .addGap(18, 18, 18)
                .addComponent(btnGestionarTecnicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarProductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProductoresActionPerformed
         JOptionPane.showMessageDialog(this, "Función en desarrollo: Gestionar Predios");
    }//GEN-LAST:event_btnGestionarProductoresActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, 
        "¿Está seeuro que desea cerrar sesión?", 
        "Confirmar", 
        JOptionPane.YES_NO_OPTION);
    
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose(); // Cerrar esta ventana
            FormLogin login = new FormLogin();
            login.setVisible(true); // Volver al login
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionarPrediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPrediosActionPerformed
        JOptionPane.showMessageDialog(this, "Función en desarrollo: Gestionar Predios");
    }//GEN-LAST:event_btnGestionarPrediosActionPerformed

    private void btnRegistrarPlagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlagaActionPerformed
        JOptionPane.showMessageDialog(this, "Función en desarrollo: Registrar Plaga");
    }//GEN-LAST:event_btnRegistrarPlagaActionPerformed

    private void btnGestionarCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCatalogosActionPerformed
        JOptionPane.showMessageDialog(this, "Función en desarrollo: Gestionar plaga y cultivos");
    }//GEN-LAST:event_btnGestionarCatalogosActionPerformed

    private void btnGestionarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTecnicosActionPerformed
        JOptionPane.showMessageDialog(this, "Función en desarrollo: Gestionar técnicos");
    }//GEN-LAST:event_btnGestionarTecnicosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void configurarMenuSegunCargo() {
        lblBienvenida.setText("Bienvenido: " + nombreUsuario);
        lblCargo.setText("Cargo: " + nombreCargo);
        
        // Mostrar/ocultar opciones según el cargo
        switch (nombreCargo) {
            case "Administrador ICA":
                // El administrador ve todo
                break;
            case "Propietario":
                btnGestionarProductores.setVisible(false);
                btnGestionarTecnicos.setVisible(false);
                btnGestionarCatalogos.setVisible(false);
                break;
            case "Productor":
                btnGestionarProductores.setVisible(false);
                btnGestionarPredios.setVisible(false);
                btnGestionarTecnicos.setVisible(false);
                btnGestionarCatalogos.setVisible(false);
                break;
            case "Asistente Técnico":
                btnGestionarProductores.setVisible(false);
                btnGestionarPredios.setVisible(false);
                btnGestionarTecnicos.setVisible(false);
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionarCatalogos;
    private javax.swing.JButton btnGestionarPredios;
    private javax.swing.JButton btnGestionarProductores;
    private javax.swing.JButton btnGestionarTecnicos;
    private javax.swing.JButton btnRegistrarPlaga;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
